"use client";

import { useEffect, useState } from "react";

const nav = ["about", "skills", "education", "projects", "experience", "contact"];
const projects = [
  { title:"E-Commerce Website", category:"JavaScript", eyebrow:"Featured frontend project", description:"A responsive shopping experience where users can explore products, view details and manage a cart through a clear, user-friendly interface.", stack:["HTML5","CSS3","JavaScript"], features:["Product browsing","Product details","Interactive shopping cart","Responsive interface"], icon:"EC", image:"https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?w=800&q=80" },
  { title:"ATM Machine Simulation", category:"Python", eyebrow:"Python logic project", description:"A menu-driven Python application that simulates essential ATM operations with transaction validation and clear error handling.", stack:["Python"], features:["PIN verification","Balance enquiry","Deposit and withdrawal","Transaction validation"], icon:"PY", image:"https://images.unsplash.com/photo-1601597111158-2fceff292cdc?w=800&q=80" },
  { title:"Library Management System", category:"SQL", eyebrow:"Python + database project", description:"A practical application for maintaining book, member, issue and return records with structured database storage.", stack:["Python","SQL"], features:["Book and member records","Search and availability","Issue and return workflow","SQL database storage"], icon:"DB", image:"https://images.unsplash.com/photo-1507842217343-583bb7270b66?w=800&q=80" },
];
const skillGroups = [
  { title:"Frontend", icon:"</>", skills:["HTML5","CSS3","JavaScript","React"] },
  { title:"Backend & Database", icon:"{ }", skills:["Python","Flask","SQL"] },
  { title:"Developer Tools", icon:"↗", skills:["Git","GitHub","Visual Studio Code"] },
  { title:"AI-Assisted Development", icon:"✦", skills:["ChatGPT","GitHub Copilot","Codex","Claude"] },
  { title:"Professional Skills", icon:"✓", skills:["Documentation","Problem Solving","Teamwork","Communication","Data Handling"] },
  { title:"Productivity", icon:"▦", skills:["MS Excel","MS Word","PowerPoint"] },
];

export default function Home() {
  const [menuOpen,setMenuOpen]=useState(false), [active,setActive]=useState("home");
  const [selectedProject,setSelectedProject]=useState<(typeof projects)[number]|null>(null), [showTop,setShowTop]=useState(false);
  useEffect(()=>{const onScroll=()=>{setShowTop(window.scrollY>650);let current="home";["home",...nav].forEach(id=>{const el=document.getElementById(id);if(el&&el.getBoundingClientRect().top<=160)current=id});setActive(current)};onScroll();window.addEventListener("scroll",onScroll,{passive:true});return()=>window.removeEventListener("scroll",onScroll)},[]);
  useEffect(()=>{if(!selectedProject)return;const close=(e:KeyboardEvent)=>e.key==="Escape"&&setSelectedProject(null);document.body.style.overflow="hidden";window.addEventListener("keydown",close);return()=>{document.body.style.overflow="";window.removeEventListener("keydown",close)}},[selectedProject]);
  return <main>
    <header className="site-header"><a className="brand" href="#home" aria-label="Ramya S home"><span>RS</span><strong>Ramya S</strong></a><button className="menu-button" aria-label="Toggle navigation" aria-expanded={menuOpen} onClick={()=>setMenuOpen(!menuOpen)}><span/><span/></button><nav className={menuOpen?"nav-links open":"nav-links"} aria-label="Primary navigation"><a className={active==="home"?"active":""} href="#home" onClick={()=>setMenuOpen(false)}>Home</a>{nav.map(item=><a key={item} className={active===item?"active":""} href={`#${item}`} onClick={()=>setMenuOpen(false)}>{item[0].toUpperCase()+item.slice(1)}</a>)}<a className="nav-cta" href="/Ramya_S_Resume.pdf" download>Resume ↓</a></nav></header>
    <section className="hero" id="home"><div className="hero-copy"><p className="availability"><span/><strong>Aspiring Python Full Stack Developer</strong></p><p className="hello">Hello, I’m Ramya S</p><h1>Building thoughtful<br/><em>web experiences.</em></h1><p className="hero-role">Python Full Stack Developer</p><p className="hero-intro">M.Sc. IT graduate creating practical, user-focused applications with React, Python, Flask and SQL—supported by proven strengths in accuracy, coordination and communication.</p><div className="hero-actions"><a className="button primary" href="#projects">View my projects ↗</a><div className="connect-group"><a className="button secondary" href="#contact">Let’s Connect</a><div className="social-icons" aria-label="Professional profiles"><a href="#" aria-label="GitHub placeholder"><SocialIcon network="github"/></a><a href="#" aria-label="LinkedIn placeholder"><SocialIcon network="linkedin"/></a></div></div></div></div><div className="hero-visual" aria-label="Profile photograph"><div className="orbit one"/><div className="orbit two"/><div className="portrait-card"><img src="/Ramya.png" alt="Ramya S" className="portrait-image" /></div><div className="floating-card right"><span>⌘</span><b>Full stack</b></div></div><a className="scroll-cue" href="#about">Scroll to explore ↓</a></section>
    <section className="section" id="about"><Heading number="01" label="About Me" title={<>A curious developer with a<br/><em>practical mindset.</em></>}/><div className="about-grid"><div className="about-copy"><p>I’m an M.Sc. Information Technology graduate building my career as a <strong>Python Full Stack Developer</strong>. I enjoy turning ideas into clear, useful web applications across the frontend and backend.</p><p>My professional background in administration, documentation and coordination has shaped how I work: with accuracy, ownership and attention to the people using a system.</p><p>I’m looking for an opportunity where I can contribute, keep learning and grow alongside an experienced development team.</p><a className="text-link" href="#contact">Start a conversation ↗</a></div><div className="highlights">{[["M.Sc.","Information Technology"],["3+","Projects"]].map(([big,small])=><article key={small}><b>{big}</b><span>{small}</span></article>)}</div></div></section>
    <section className="section skills" id="skills"><Heading number="02" label="Technical Toolkit" title={<>Technologies I use to<br/><em>bring ideas to life.</em></>}/><div className="skills-grid">{skillGroups.map((g,index)=><article className="skill-card" key={g.title}><div className={`skill-visual visual-${index+1}`} role="img" aria-label={`${g.title} technology visual`}/><div className="skill-card-body"><div className="skill-icon">{g.icon}</div><h3>{g.title}</h3><div className="tags">{g.skills.map(s=><span key={s}>{s}</span>)}</div></div></article>)}</div></section>
    <section className="section" id="education"><Heading number="03" label="Education" title={<>Developed a strong foundation in programming, databases, and software development.</>}/><div className="education-grid"><Education year="2019" degree="M.Sc. Information Technology" place="Pavendar Bharathidasan College of Arts and Science, Trichy"/><Education year="2016" degree="Bachelor of Computer Applications" place="Computer Applications"/></div><div className="achievement"><span>★</span><div><p>Achievement</p><h3>First Prize — College Debugging Competition</h3><small>Recognised for logical thinking, debugging ability and problem-solving.</small></div></div></section>
    <section className="section projects" id="projects"><Heading number="04" label="Featured Projects" title={<>Practical work that shows<br/><em>how I think and build.</em></>}/><div className="projects-grid">{projects.map((p,i)=><article className={`project-card p${i+1}`} key={p.title}><div className="project-visual" style={{backgroundImage:`url('${p.image}')`}}><span>{p.icon}</span></div><div className="project-content"><p>{p.eyebrow}</p><h3>{p.title}</h3><p className="desc">{p.description}</p><div className="project-tags">{p.stack.map(x=><span key={x}>{x}</span>)}</div><div className="project-links"><button onClick={()=>setSelectedProject(p)}>View details ↗</button><a href="#" aria-label={`${p.title} GitHub placeholder`}>GitHub</a></div></div></article>)}</div></section>
    <section className="section" id="experience"><Heading number="05" label="Experience" title={<>Professional experience,<br/><em>transferable strengths.</em></>}/><div className="timeline"><Work date="2023 — 2024" company="Maxi Vision Eye Hospital" role="HR Assistant" text="Supported HR and front-office operations including staff coordination, attendance and records maintenance, patient and employee data, and administrative documentation." tags={["Coordination","Records","Documentation"]}/><Work date="2019 — 2023" company="C.A.R.E School of Architecture, Trichy" role="Exam Cell Assistant" text="Maintained academic records, supported examination scheduling, performed accurate data entry and coordinated clearly with staff and students." tags={["Data entry","Scheduling","Reporting"]}/></div><div className="transferable"><span>↳</span><div><p>How my experience supports development</p><h3>Accuracy, organization and communication are part of good software too.</h3></div><p>I bring a dependable working style: documenting clearly, solving problems calmly, coordinating with people and taking responsibility for details.</p></div></section>
    <section className="contact" id="contact"><div className="section contact-inner">
      <div className="contact-heading"><p className="kicker"><span>06</span> Let’s connect</p><h2>Get In <em>Touch</em></h2><i/><p>Have an opportunity, project, or Python full stack role in mind? I’d love to hear from you.</p></div>
      <div className="contact-cards">
        <article className="contact-card"><h3>Contact Information</h3><div className="detail-row"><span className="detail-icon">✉</span><div><b>Email Me</b><a href="mailto:ramyaselvaraj214@gmail.com">ramyaselvaraj214@gmail.com</a></div></div><div className="detail-row"><span className="detail-icon">⌖</span><div><b>Location</b><p>Tiruchirappalli, Tamil Nadu</p><small>Available for onsite and remote work</small></div></div><div className="detail-row"><span className="detail-icon">☎</span><div><b>Phone</b><a href="tel:+916380768574">+91 6380768574</a></div></div></article>
        <article className="contact-card"><h3>Professional Details</h3><div className="detail-row"><span className="detail-icon">⌂</span><div><b>Education</b><p>M.Sc. Information Technology</p><small>Pavendar Bharathidasan College, Trichy</small></div></div><div className="detail-row"><span className="detail-icon">▣</span><div><b>Availability</b><p>Open to Python Full Stack roles</p><small>Junior Developer · Flask · Frontend</small></div></div><div className="detail-row"><span className="detail-icon">✓</span><div><b>Languages</b><p>Tamil · English · Hindi</p></div></div></article>
      </div>
      <div className="collaborate-card"><h3>Let’s Collaborate</h3><p>I’m actively seeking opportunities in Python full stack development. Whether you have a junior developer role, a web project, or would simply like to discuss building practical applications, I’m excited to connect and explore the possibilities.</p><a href="mailto:ramyaselvaraj214@gmail.com">Start a conversation <span>↗</span></a></div>
    </div></section>
    <footer><a className="brand" href="#home"><span>RS</span><strong>Ramya S</strong></a><p>Python Full Stack Developer</p><div><a href="#projects">Projects</a><a href="#experience">Experience</a><a href="#contact">Contact</a><a href="#">GitHub</a><a href="#">LinkedIn</a></div><small>© {new Date().getFullYear()} Designed & developed by Ramya S</small></footer>
    {selectedProject&&<div className="modal-backdrop" onMouseDown={()=>setSelectedProject(null)}><div className="project-modal" role="dialog" aria-modal="true" aria-labelledby="modal-title" onMouseDown={e=>e.stopPropagation()}><button className="modal-close" onClick={()=>setSelectedProject(null)} aria-label="Close project details">×</button><p>{selectedProject.eyebrow}</p><h2 id="modal-title">{selectedProject.title}</h2><p>{selectedProject.description}</p><h3>Key features</h3><ul>{selectedProject.features.map(f=><li key={f}>{f}</li>)}</ul><div className="project-tags">{selectedProject.stack.map(x=><span key={x}>{x}</span>)}</div><div className="modal-actions"><a className="button primary" href="#">GitHub placeholder ↗</a><button className="button secondary" onClick={()=>setSelectedProject(null)}>Close</button></div></div></div>}{showTop&&<button className="scroll-top" aria-label="Back to top" onClick={()=>window.scrollTo({top:0,behavior:"smooth"})}>↑</button>}
  </main>
}
function Heading({number,label,title}:{number:string;label:string;title:React.ReactNode}){return <div className="section-heading"><div className="section-title"><span>{number}</span><h2>{label}</h2></div><div className="section-subtitle">{title}</div></div>}
function Education({year,degree,place}:{year:string;degree:string;place:string}){return <article><span>{year}</span><div><p>Academic qualification</p><h3>{degree}</h3><small>{place}</small></div></article>}
function Work({date,company,role,text,tags}:{date:string;company:string;role:string;text:string;tags:string[]}){return <article><div className="timeline-date">{date}</div><i/><div><p>{company}</p><h3>{role}</h3><p>{text}</p><div className="work-tags">{tags.map(t=><span key={t}>{t}</span>)}</div></div></article>}
function SocialIcon({network}:{network:"github"|"linkedin"}){return network==="github"?<svg viewBox="0 0 24 24" aria-hidden="true"><path fill="currentColor" d="M12 .7A11.3 11.3 0 0 0 8.4 22.8c.6.1.8-.2.8-.6v-2.1c-3.4.7-4.1-1.4-4.1-1.4-.6-1.4-1.4-1.8-1.4-1.8-1.1-.8.1-.8.1-.8 1.2.1 1.9 1.3 1.9 1.3 1.1 1.9 2.9 1.3 3.6 1 .1-.8.4-1.3.8-1.6-2.7-.3-5.5-1.4-5.5-6a4.7 4.7 0 0 1 1.3-3.3 4.4 4.4 0 0 1 .1-3.3s1-.3 3.4 1.3a11.7 11.7 0 0 1 6.2 0c2.4-1.6 3.4-1.3 3.4-1.3a4.4 4.4 0 0 1 .1 3.3 4.7 4.7 0 0 1 1.3 3.3c0 4.7-2.8 5.7-5.5 6 .4.4.8 1.1.8 2.2v3.2c0 .4.2.7.8.6A11.3 11.3 0 0 0 12 .7Z"/></svg>:<svg viewBox="0 0 24 24" aria-hidden="true"><path fill="currentColor" d="M5.2 7.8H1.6V22h3.6V7.8ZM3.4 2A2.1 2.1 0 1 0 3.4 6.2 2.1 2.1 0 0 0 3.4 2Zm19 11.9c0-4.3-2.3-6.3-5.4-6.3a4.7 4.7 0 0 0-4.2 2.3V7.8H9.2V22h3.6v-7c0-1.9.4-3.7 2.7-3.7 2.3 0 2.3 2.1 2.3 3.8V22h3.6l1-8.1Z"/></svg>}
